[workspace]
resolver = "2"
members = [
  "celkit",
  "celkit_core",
  "celkit_string",
  "celkit_binary",
  "celkit_derive",
]

[workspace.package]
version = "0.1.0"
authors = ["Mohsen Rad (🌱) <irregular.celery@gmail.com>"]
edition = "2021"
license = "MIT"
